#!/usr/bin/env bash

chromium_git="https://chromium.googlesource.com"
v8_dir="deps/v8"

error() {
  echo $*
  exit 1
}

[ ! -e ${v8_dir} ] || error "${v8_dir} already exists"

remote=$(git ls-remote --get-url origin)
if [[ ! ${remote} =~ github.com.nodejs.node ]]; then
  error "current directory is not a clone of github.com/nodejs/node"
fi

[ $# -eq 1 ] || error "Usage: $0 v8_commit_ish"
v8_commit=$1

# fetch_from_git git_url git_repo directory commit keep_dot_git
fetch_from_git() {
  git_url=$1
  git_repo=$2
  dir=$3
  commit=$4
  keep_dot_git=$5

  [ ! -e ${dir} ]    || error "${dir} already exists"
  [ ! -z ${commit} ] || error "commit not specified"

  mkdir -p ${dir}
  pushd ${dir}
  git init
  git remote add origin ${git_url}${git_repo}
  git fetch origin ${commit}
  git reset --hard FETCH_HEAD
  if [ -z ${keep_dot_git} ]; then
    rm -rf .git
  fi
  popd
}

# get_v8_dep name repo_name destination
get_v8_dep() {
  name=$1
  repo_name=$2
  destination=$3

  pushd ${v8_dir}
  repo=$(  grep ${repo_name} DEPS | awk -F+ '{print $2}' | tr -d " \",")
  commit=$(grep ${repo_name} DEPS | awk -F+ '{print $4}' | tr -d " \",")
  fetch_from_git ${chromium_git} ${repo} ${destination} ${commit}
  echo "Update ${name} to ${commit}"
  popd

  git add "${v8_dir}/${destination}"
  git commit -m "deps: update V8 dep ${name} to ${commit}"
}

fetch_from_git ${chromium_git} "/v8/v8.git" ${v8_dir} ${v8_commit} "keep"

[ -d ${v8_dir} ] || (echo "unable to fetch v8" ; exit 1)

# Edit .gitignore
sed -i.bak "/\/base/d" ${v8_dir}/.gitignore
sed -i.bak "s#^/testing/gtest#/testing/gtest/*\n!/testing/gtest/include\n/testing/gtest/include/*\n!/testing/gtest/include/gtest\n/testing/gtest/include/gtest/*\n!/testing/gtest/include/gtest/gtest_prod.h#" ${v8_dir}/.gitignore
echo "!/third_party/jinja2" >> ${v8_dir}/.gitignore
echo "!/third_party/markupsafe" >> ${v8_dir}/.gitignore

# Commit the v8 update
git add deps/v8
git commit -m "deps: update V8 to ${v8_commit}"

# fetch V8 DEPS that we need to build Node
get_v8_dep "trace_event" "trace_event/common.git" "base/trace_event/common"
get_v8_dep "gtest" "google/googletest.git" "testing/gtest"
get_v8_dep "jinja2" "src/third_party/jinja2.git" "third_party/jinja2"
get_v8_dep "markupsafe" "src/third_party/markupsafe.git" "third_party/markupsafe"
